[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd server && npm start"
